spring:
  application:
    name: demo

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    properties:
      hibernate:
        dialect: ${SPRING_JPA_HIBERNATE_DIALECT}

    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO}

    show-sql: ${SPRING_JPA}

server:
  port: ${SERVER_PORT}